name: Publish to MCP Registry

on:
  push:
    tags:
      - "v*.*.*"  # Triggers on version tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for GitHub OIDC authentication
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test || echo "No tests found, skipping"

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install and use MCP Publisher
        run: |
          # Clone the MCP registry repo to get the publisher tool
          git clone https://github.com/modelcontextprotocol/registry.git /tmp/mcp-registry
          cd /tmp/mcp-registry

          # Build the publisher tool
          make publisher

          # Use the publisher to publish our server
          ./bin/mcp-publisher login github-oidc

          # Go back to our repo and publish
          cd $GITHUB_WORKSPACE
          /tmp/mcp-registry/bin/mcp-publisher publish